src/api/urls.py
from django.conf.urls import patterns, include, url
from rest_framework.routers import DefaultRouter

from .courses.views import CourseViewSet, ModuleViewSet
from .materials.views import MaterialViewSet, ExampleMaterialViewSet, \
    DefinitionMaterialViewSet, ProofMaterialViewSet, \
    TheoremMaterialViewSet
from .theory.views import TheoremViewSet, DefinitionViewSet, \
    ExerciseViewSet, ProofViewSet

router = DefaultRouter()
router.register(r'courses', CourseViewSet)
router.register(r'modules', ModuleViewSet)

router.register(r'materials', MaterialViewSet)

router.register(r'exampleMaterials', ExampleMaterialViewSet)
router.register(r'proofMaterials', ProofMaterialViewSet)
router.register(r'definitionMaterials', DefinitionMaterialViewSet)
router.register(r'theoremMaterials', TheoremMaterialViewSet)

router.register(r'proofs', ProofViewSet)
router.register(r'exercises', ExerciseViewSet)
router.register(r'definitions', DefinitionViewSet)
router.register(r'theorems', TheoremViewSet)

urlpatterns = patterns('',

                       url(r'^', include(router.urls)),
                       )

src/generatorKursow/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns(
    '',

    url(r'^', include('web.urls', namespace='web')),

    url(r'^theory/', include('apps.theory.urls', namespace='theory')),
    url(r'^course/', include('apps.course.urls', namespace='course')),
    url(r'^module/', include('apps.module.urls', namespace='module')),
    url(r'^material/', include('apps.material.urls', namespace='material')),
    url(r'^interactivity/', include('apps.interactivity.urls', namespace='interactivity')),

    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^docs/', include('rest_framework_swagger.urls')),

    url(r'^account/plugins/', include('plugins.urls', namespace="plugins")),
    url(r'^account/templates/', include('userTemplates.urls', namespace='userTemplates')),
    url(r'^login', 'django.contrib.auth.views.login', name="login"),
    url(r'^logout', 'django.contrib.auth.views.logout', {'next_page': '/'}, name="logout"),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^accounts/', include('registration.backends.simple.urls', namespace='accounts')),

    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

src/plugins/urls.py
from django.conf.urls import patterns, url

from plugins import views

urlpatterns = patterns(
    '',

    url(r'^$', views.IndexView.as_view(), name="index"),
    url(r'^refresh/$', views.refresh, name="refresh"),
    url(r'^(?P<pk>[\d]+)/del/$', views.PluginDeleteView.as_view(), name="delete"),
    # url(r'^(?P<pk>[\d]+)/activate/$', views.ActivateView.as_view(), name="activate"),

)

src/web/templates/tags/interactive_element_display.html
{% for field in form %}

    <dl class="dl-horizontal">
        <dt>{{ field.label }}:</dt>
        <dd>{{ field.value | safe }}</dd>
    </dl>

{% endfor %}

src/web/templates/tags/nav_menu.html
<!-- Navigation -->
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" ui-sref="home">Generator kursów</a>
    </div>
    <!-- /.navbar-header -->
    <ul class="nav navbar-top-links navbar-right">
        {{ username }}

        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                <li>
                    <a href="{% url 'plugins:index' %}"><i class="fa fa-plug fa-fw"></i> Pluginy</a>
                </li>
                <li>
                    <a href="{% url 'userTemplates:index' %}"><i class="fa fa-files-o fa-fw"></i> Szablony</a>
                </li>
                <li class="divider"></li>
                <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out fa-fw"></i> Wyloguj</a>
                </li>
            </ul>
            <!-- /.dropdown-user -->
        </li>
        <!-- /.dropdown -->
    </ul>
    <!-- /.navbar-top-links -->
    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">

                {% for item in menuitems %}

                    <li {% if item.active %}class="active"{% endif %}>
                        <a href="{{ item.url }}">
                            <i class="fa {{ item.icon }}"></i>
                            <span>{{ item.title }}</span>
                            {% if item.children %} <span class="fa arrow"></span> {% endif %}
                        </a>

                        {% if item.children %}
                            <ul class="nav nav-second-level" aria-expanded="false" style="height: 0px;">
                                {% for child in item.children %}
                                    <li>
                                        <a href="{{ child.url }}">
                                            <i class="fa {{ child.icon }}"></i>
                                            {{ child.title }}
                                        </a>
                                    </li>
                                {% endfor %}
                            </ul>

                        {% endif %}
                    </li>

                {% endfor %}
            </ul>
        </div>
        <!-- /.sidebar-collapse -->
    </div>
    <!-- /.navbar-static-side -->
</nav>