src/api/urls.py
from django.conf.urls import patterns, include, url
from rest_framework.routers import DefaultRouter

from .courses.views import CourseViewSet, ModuleViewSet
from .materials.views import MaterialViewSet, ExampleMaterialViewSet, \
    DefinitionMaterialViewSet, ProofMaterialViewSet, \
    TheoremMaterialViewSet
from .theory.views import TheoremViewSet, DefinitionViewSet, \
    ExerciseViewSet, ProofViewSet

router = DefaultRouter()
router.register(r'courses', CourseViewSet)
router.register(r'modules', ModuleViewSet)

router.register(r'materials', MaterialViewSet)

router.register(r'exampleMaterials', ExampleMaterialViewSet)
router.register(r'proofMaterials', ProofMaterialViewSet)
router.register(r'definitionMaterials', DefinitionMaterialViewSet)
router.register(r'theoremMaterials', TheoremMaterialViewSet)

router.register(r'proofs', ProofViewSet)
router.register(r'exercises', ExerciseViewSet)
router.register(r'definitions', DefinitionViewSet)
router.register(r'theorems', TheoremViewSet)

urlpatterns = patterns('',

                       url(r'^', include(router.urls)),
                       )

src/generatorKursow/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns(
    '',

    url(r'^', include('web.urls', namespace='web')),

    url(r'^theory/', include('apps.theory.urls', namespace='theory')),
    url(r'^course/', include('apps.course.urls', namespace='course')),
    url(r'^module/', include('apps.module.urls', namespace='module')),
    url(r'^material/', include('apps.material.urls', namespace='material')),
    url(r'^interactivity/', include('apps.interactivity.urls', namespace='interactivity')),

    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^docs/', include('rest_framework_swagger.urls')),

    url(r'^account/plugins/', include('plugins.urls', namespace="plugins")),
    url(r'^account/templates/', include('userTemplates.urls', namespace='userTemplates')),
    url(r'^login', 'django.contrib.auth.views.login', name="login"),
    url(r'^logout', 'django.contrib.auth.views.logout', {'next_page': '/'}, name="logout"),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^accounts/', include('registration.backends.simple.urls', namespace='accounts')),

    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

src/web/urls.py
from django.conf.urls import patterns, url

from web.views import *


urlpatterns = patterns(
        '',

        url(r'^$',
            home,
            name='home'),

        url(r'^download/course/(?P<id>[\d]+)/$',
            choose_course_template,
            name='download-course'),
        url(r'^download/module/(?P<id>[\d]+)/$',
            choose_module_template,
            name='download-module'),
        url(r'^download/material/(?P<id>[\d]+)/$',
            choose_material_template,
            name='download-material'),

        url(r'^download/(?P<item_type>course|module|material)/(?P<id>[\d]+)/without/template/$',
            download,
            name='download-without-template'),
        url(
            r'^download/(?P<item_type>course|module|material)/(?P<id>[\d]+)/using/template/(?P<template_name>[A-Za-z]+)/$',
            download,
            name='download-using-template'),

        url(r'^preview/(?P<item_type>course|module|material)/(?P<id>[\d]+)/$',
            preview,
            name='preview')

)

src/web/templates/base/modal_form.html
{% extends "web/base_modal.html" %}

{% load crispy_forms_tags formset_tags pdb_filter %}

{% block modal_content %}

    {% if form.formsets %}

        {% for formset in form.formsets %}
            <div class="formset" data-formset-prefix="{{ formset.prefix }}">
                {{ formset.management_form }}

                {% crispy form %}

                <div data-formset-body>
                    <!-- New forms will be inserted in here -->
                    {% for inline_form in formset %}
                        <div data-formset-form>
                            {% include "interactivity/form.html" with form=inline_form %}
                        </div>
                    {% endfor %}
                </div>

                <!-- The empty form template. By wrapping this in a <script> tag, the
                __prefix__ placeholder can easily be replaced in both attributes and
                any scripts -->
                <script type="form-template" data-formset-empty-form>
                    {% escapescript %}
                        <div data-formset-form>
                            {% crispy formset.empty_form %}
                            <div class="hidden">{{ formset.DELETE }}</div>
                            <button type="button" data-formset-delete-button>Delete form</button>
                        </div>
                    {% endescapescript %}
                </script>
                {{ formset.media }}
                <script>
                    $(".formset").formset({
                        animateForms: true
                    });
                </script>

                <!-- This button will add a new form when clicked -->
                <input type="button" value="Dodaj odpowiedź" data-formset-add>

            </div>

        {% endfor %}

    {% else %}

        {% crispy form %}

    {% endif %}

{% endblock %}

src/web/templates/base/object_detail.html
{% extends "web/base.html" %}

{% load web_tags %}

{% block content %}
    <legend>
        {% block object_title %}
            {% if object|is_private %}
                <span class="label label-info">Prywatny</span>
            {% else %}
                <span class="label label-warning">Publiczny</span>
            {% endif %}
            {{ title }}: {{ object.title }}
        {% endblock %}
    </legend>
    <div class="panel panel-default">
        <div class="panel-heading">
            Dane podstawowe
        </div>
        <div class="panel-body form-horizontal">
            <div class="has-feedback form-group">
                <label class="col-sm-2 control-label">Tytuł:</label>
                <div class="col-sm-10">
                    <p class="form-control-static">{{ object.title }}</p>
                </div>
            </div>
            <div class="has-feedback form-group">
                <label class="col-sm-2 control-label">Opis:</label>
                <div class="col-sm-10">
                    <p class="form-control-static">{{ object.description | safe }}</p>
                </div>
            </div>
            {% block extra_base_data %}
            {% endblock %}
        </div>
    </div>

    {% block extra_panels %}
    {% endblock %}


    {% if object|is_my:request.user %}
        <a href="{{ object.get_absolute_edit_url }}" class="btn btn-primary">Edytuj</a>
        <a href="{{ object.get_absolute_delete_url }}" class="btn btn-danger modal_runner">Usuń</a>
    {% endif %}
    {% block preview %}
        <a href="{{ object.get_absolute_preview_url }}" class="btn btn-success">Podejrzyj</a>
    {% endblock %}

    {% if object|is_my:request.user %}
        {% block publish_private %}
            {% if object|is_private %}
                <a href="{{ object.get_absolute_publish_url }}" class="btn btn-warning modal_runner">Opublikuj</a>
            {% else %}
                <a href="{{ object.get_absolute_private_url }}" class="btn btn-info modal_runner">Uprywatnij</a>
            {% endif %}
        {% endblock %}
    {% endif %}


{% endblock %}

src/web/templates/base/object_form.html
{% extends "web/base.html" %}

{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Dane podstawowe
                    </div>

                    <div class="panel-body">

                        <fieldset role="tabpanel" class="tab-pane active" id="base_data">
                            <div class="form-horizontal">
                                {% load crispy_forms_tags %}
                                {% crispy form %}
                            </div>
                        </fieldset>
                    </div>
                </div>
            </div>

            {% block extra_panels %}
            {% endblock %}

            <div class="clearfix"></div>
            <hr>
            <input type="submit" value="Zapisz" class="btn btn-success">
            <a href="{{ object.get_absolute_url }}" class="btn btn-danger">Anuluj</a>

        </div>
    </form>
{% endblock %}

src/web/templates/base/object_list.html
{% extends "web/base.html" %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                {% block title %}
                    {{ title }}
                {% endblock %}

                {% block add_new %}
                    <a href="{% url 'web:home' %}" class="btn btn-primary">Dodaj nowy</a>
                {% endblock %}
            </h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Moje {{ title }}
                </div>
                <div class="panel-body">
                    <div class="dataTable_wrapper">
                        <table class="table table-striped table-bordered table-hover dataTable">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Tytuł</th>
                                <th>Autor</th>
                                <th>Opis</th>
                                {% block additional_th %}{% endblock %}
                                <th>Opcje</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for object in my_objects %}
                                <tr>
                                    <td>{{ object.id }}</td>
                                    <td>
                                        <a href="{{ object.get_absolute_url }}">{{ object.title }}</a>
                                    </td>
                                    <td>{{ object.createdBy }}</td>
                                    <td>{{ object.description | truncatewords:5 }}</td>
                                    {% block additional_td %}
                                    {% endblock %}
                                    <td>
                                        {% load web_tags %}
                                        {% if object|is_course %}
                                            <a class="fa fa-file-archive-o"
                                               href="{% url 'web:download-course' object.pk %}">Pobierz</a>
                                        {% elif object|is_module %}
                                            <a class="fa fa-file-archive-o"
                                               href="{% url 'web:download-module' object.pk %}">Pobierz</a>
                                        {% elif object|is_material %}
                                            <a class="fa fa-file-archive-o"
                                               href="{% url 'web:download-material' object.pk %}">Pobierz</a>
                                        {% endif %}
                                        <a href="{{ object.get_absolute_delete_url }}" class="modal_runner">Usuń</a>
                                        {% block preview %}
                                        {% endblock %}
                                    </td>
                                </tr>
                            {% endfor %}

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% if public_objects %}

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Publiczne {{ title }}
                    </div>
                    <div class="panel-body">
                        <div class="dataTable_wrapper">
                            <table class="table table-striped table-bordered table-hover dataTable">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Tytuł</th>
                                    <th>Autor</th>
                                    <th>Opis</th>
                                    {% block public_additional_th %}{% endblock %}
                                    <th>Opcje</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for object in public_objects %}
                                    <tr>
                                        <td>{{ object.id }}</td>
                                        <td>
                                            <a href="{{ object.get_absolute_url }}">{{ object.title }}</a>
                                        </td>
                                        <td>{{ object.createdBy }}</td>
                                        <td>{{ object.description | truncatewords:5 }}</td>
                                        {% block public_additional_td %}{% endblock %}
                                        <td>
                                            {% load web_tags %}
                                            {% if object|is_course %}
                                                <a class="fa fa-file-archive-o"
                                                   href="{% url 'web:download-course' object.pk %}">Pobierz</a>
                                            {% elif object|is_module %}
                                                <a class="fa fa-file-archive-o"
                                                   href="{% url 'web:download-module' object.pk %}">Pobierz</a>
                                            {% elif object|is_material %}
                                                <a class="fa fa-file-archive-o"
                                                   href="{% url 'web:download-material' object.pk %}">Pobierz</a>
                                            {% endif %}
                                            {% block public_preview %}{% endblock %}
                                        </td>
                                    </tr>
                                {% endfor %}

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    {% endif %}

{% endblock %}

src/web/templates/base/type_choice.html
{% extends "web/base.html" %}

{% block content %}
    <div class="row">
        <h1 class="page-header">
            {% block title %}
                {{ title }}
            {% endblock %}
        </h1>
    </div>
    <div class="row">
        {% block buttons %}
        {% endblock %}
    </div>

{% endblock %}