src/api/urls.py
from django.conf.urls import patterns, include, url
from rest_framework.routers import DefaultRouter

from .courses.views import CourseViewSet, ModuleViewSet
from .materials.views import MaterialViewSet, ExampleMaterialViewSet, \
    DefinitionMaterialViewSet, ProofMaterialViewSet, \
    TheoremMaterialViewSet
from .theory.views import TheoremViewSet, DefinitionViewSet, \
    ExerciseViewSet, ProofViewSet

router = DefaultRouter()
router.register(r'courses', CourseViewSet)
router.register(r'modules', ModuleViewSet)

router.register(r'materials', MaterialViewSet)

router.register(r'exampleMaterials', ExampleMaterialViewSet)
router.register(r'proofMaterials', ProofMaterialViewSet)
router.register(r'definitionMaterials', DefinitionMaterialViewSet)
router.register(r'theoremMaterials', TheoremMaterialViewSet)

router.register(r'proofs', ProofViewSet)
router.register(r'exercises', ExerciseViewSet)
router.register(r'definitions', DefinitionViewSet)
router.register(r'theorems', TheoremViewSet)

urlpatterns = patterns('',

                       url(r'^', include(router.urls)),
                       )

src/apps/material/urls.py
from django.conf.urls import patterns, include, url
from .views import definition as definition_views
from .views import example as example_views
from .views import proof as proof_views
from .views import theorem as theorem_views
from .views import material as material_views


definition_patterns = patterns(
    '',

    url(r'^(?P<pk>[0-9]+)/edit/$', definition_views.DefinitionMaterialUpdate.as_view(), name='edit'),
    url(r'^new/$', definition_views.DefinitionMaterialCreate.as_view(), name='new'),
)

example_patterns = patterns(
    '',

    url(r'^(?P<pk>[0-9]+)/edit/$', example_views.ExampleMaterialUpdate.as_view(), name='edit'),
    url(r'^new/$', example_views.ExampleMaterialCreate.as_view(), name='new'),
)

proof_patterns = patterns(
    '',

    url(r'^(?P<pk>[0-9]+)/edit/$', proof_views.ProofMaterialUpdate.as_view(), name='edit'),
    url(r'^new/$', proof_views.ProofMaterialCreate.as_view(), name='new'),
)

theorem_patterns = patterns(
    '',

    url(r'^(?P<pk>[0-9]+)/edit/$', theorem_views.TheoremMaterialUpdate.as_view(), name='edit'),
    url(r'^new/$', theorem_views.TheoremMaterialCreate.as_view(), name='new'),
)


urlpatterns = patterns(
    '',

    url(r'^$', material_views.MaterialList.as_view(), name='list'),
    url(r'^(?P<pk>[0-9]+)/$', material_views.MaterialDetail.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/delete/', material_views.MaterialDelete.as_view(), name='delete'),
    url(r'^(?P<pk>[0-9]+)/publish/', material_views.MaterialPublish.as_view(), name='publish'),
    url(r'^(?P<pk>[0-9]+)/private/', material_views.MaterialPrivate.as_view(), name='private'),
    url(r'^new/$', material_views.MaterialCreateChoice.as_view(), name='new'),

    url(r'^definition/', include(definition_patterns, namespace='definition')),
    url(r'^example/', include(example_patterns, namespace='example')),
    url(r'^proof/', include(proof_patterns, namespace='proof')),
    url(r'^theorem/', include(theorem_patterns, namespace='theorem')),

)

src/generatorKursow/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns(
    '',

    url(r'^', include('web.urls', namespace='web')),

    url(r'^theory/', include('apps.theory.urls', namespace='theory')),
    url(r'^course/', include('apps.course.urls', namespace='course')),
    url(r'^module/', include('apps.module.urls', namespace='module')),
    url(r'^material/', include('apps.material.urls', namespace='material')),
    url(r'^interactivity/', include('apps.interactivity.urls', namespace='interactivity')),

    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^docs/', include('rest_framework_swagger.urls')),

    url(r'^account/plugins/', include('plugins.urls', namespace="plugins")),
    url(r'^account/templates/', include('userTemplates.urls', namespace='userTemplates')),
    url(r'^login', 'django.contrib.auth.views.login', name="login"),
    url(r'^logout', 'django.contrib.auth.views.logout', {'next_page': '/'}, name="logout"),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^accounts/', include('registration.backends.simple.urls', namespace='accounts')),

    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

src/web/urls.py
from django.conf.urls import patterns, url

from web.views import *


urlpatterns = patterns(
        '',

        url(r'^$',
            home,
            name='home'),

        url(r'^download/course/(?P<id>[\d]+)/$',
            choose_course_template,
            name='download-course'),
        url(r'^download/module/(?P<id>[\d]+)/$',
            choose_module_template,
            name='download-module'),
        url(r'^download/material/(?P<id>[\d]+)/$',
            choose_material_template,
            name='download-material'),

        url(r'^download/(?P<item_type>course|module|material)/(?P<id>[\d]+)/without/template/$',
            download,
            name='download-without-template'),
        url(
            r'^download/(?P<item_type>course|module|material)/(?P<id>[\d]+)/using/template/(?P<template_name>[A-Za-z]+)/$',
            download,
            name='download-using-template'),

        url(r'^preview/(?P<item_type>course|module|material)/(?P<id>[\d]+)/$',
            preview,
            name='preview')

)

src/apps/material/forms.py
from apps.common.forms import BaseCrispyForm, DEFAULT_EXCLUDE_FIELDS
from apps.material.models import TheoremMaterial, ProofMaterial, DefinitionMaterial, ExampleMaterial
from apps.theory.models import Proof, Definition, Theorem

DEFAULT_MATERIAL_EXCLUDE_FIELDS = DEFAULT_EXCLUDE_FIELDS + ('interactiveElements',)


class TheoremMaterialForm(BaseCrispyForm):

    def __init__(self, *args, **kwargs):
        super(TheoremMaterialForm, self).__init__(*args, **kwargs)
        self.fields['theorem'].queryset = Theorem.visible_manager.visible(self.request_user)

    class Meta:
        model = TheoremMaterial
        exclude = DEFAULT_MATERIAL_EXCLUDE_FIELDS


class ProofMaterialForm(BaseCrispyForm):

    def __init__(self, *args, **kwargs):
        super(ProofMaterialForm, self).__init__(*args, **kwargs)
        self.fields['proof'].queryset = Proof.visible_manager.visible(self.request_user)

    class Meta:
        model = ProofMaterial
        exclude = DEFAULT_MATERIAL_EXCLUDE_FIELDS


class DefinitionMaterialForm(BaseCrispyForm):

    def __init__(self, *args, **kwargs):
        super(DefinitionMaterialForm, self).__init__(*args, **kwargs)
        self.fields['definition'].queryset = Definition.visible_manager.visible(self.request_user)

    class Meta:
        model = DefinitionMaterial
        exclude = DEFAULT_MATERIAL_EXCLUDE_FIELDS


class ExampleMaterialForm(BaseCrispyForm):

    class Meta:
        model = ExampleMaterial
        exclude = DEFAULT_MATERIAL_EXCLUDE_FIELDS

src/api/materials/views.py
from rest_framework import viewsets

from apps.material.models import Material, ExampleMaterial, TheoremMaterial, ProofMaterial, \
    DefinitionMaterial
from api.materials.serializers import MaterialSerializer, ExampleMaterialSerializer, \
    TheoremMaterialSerializer, ProofMaterialSerializer, \
    DefinitionMaterialSerializer


class MaterialViewSet(viewsets.ReadOnlyModelViewSet):

    queryset = Material.objects.all()
    serializer_class = MaterialSerializer


class ExampleMaterialViewSet(viewsets.ModelViewSet):

    queryset = ExampleMaterial.objects.all()
    serializer_class = ExampleMaterialSerializer


class TheoremMaterialViewSet(viewsets.ModelViewSet):

    queryset = TheoremMaterial.objects.all()
    serializer_class = TheoremMaterialSerializer


class ProofMaterialViewSet(viewsets.ModelViewSet):

    queryset = ProofMaterial.objects.all()
    serializer_class = ProofMaterialSerializer


class DefinitionMaterialViewSet(viewsets.ModelViewSet):

    queryset = DefinitionMaterial.objects.all()
    serializer_class = DefinitionMaterialSerializer

src/apps/material/views/definition.py
from apps.material.forms import DefinitionMaterialForm
from apps.material.models import DefinitionMaterial
from apps.material.views.material import BaseMaterialCreate, BaseMaterialUpdate


class DefinitionMaterialCreate(BaseMaterialCreate):
    model = DefinitionMaterial
    form_class = DefinitionMaterialForm


class DefinitionMaterialUpdate(BaseMaterialUpdate):
    model = DefinitionMaterial
    form_class = DefinitionMaterialForm

src/apps/material/views/example.py
from apps.material.forms import ExampleMaterialForm
from apps.material.models import ExampleMaterial
from apps.material.views.material import BaseMaterialCreate, BaseMaterialUpdate


class ExampleMaterialCreate(BaseMaterialCreate):
    model = ExampleMaterial
    form_class = ExampleMaterialForm


class ExampleMaterialUpdate(BaseMaterialUpdate):
    model = ExampleMaterial
    form_class = ExampleMaterialForm

src/apps/material/views/material.py
# -*- coding: utf-8 -*-
from apps.common.views import *
from django.core.urlresolvers import reverse_lazy
from django.http import QueryDict

from apps.interactivity.forms import InteractiveElementForm
from apps.interactivity.models import InteractiveElement
from django.shortcuts import redirect
from apps.material.forms import TheoremMaterialForm
from apps.material.models import Material


class MaterialList(BaseListView):
    model = Material
    title = 'Materiały'
    

class MaterialDetail(BaseDetailView):
    model = Material
    template_name = "material/detail.html"
    title = 'Materiał'


class MaterialDelete(BaseDeleteView):
    model = Material
    success_url = reverse_lazy('material:list')


class MaterialPublish(BasePublishView):
    model = Material


class MaterialPrivate(BasePrivateView):
    model = Material


class MaterialCreateChoice(BaseCreateChoice):
    template_name = "material/material_choice.html"


class BaseMaterialCreate(BaseCreateView):
    template_name = "material/material_form.html"
    form_list = []
    page_title = "Nowy materiał"

    def get_context_data(self, **kwargs):
        context = super(BaseMaterialCreate, self).get_context_data(**kwargs)

        form_list = kwargs.get('form_list', [])

        if form_list:
            form_list.sort(key=lambda x: x.form_number)

        context.update({
            'interactive_elements': InteractiveElementForm.get_interactive_elements(),
            'form_list': form_list,
            'page_title': self.page_title
        })

        return context

    def form_invalid(self, form, form_list=None):
        return self.render_to_response(self.get_context_data(form=form, form_list=form_list))

    def post(self, request, *args, **kwargs):
        self.object = None
        form_list = []

        form = self.form_class(user=self.request.user, data=request.POST)

        number_list = []
        for key in request.POST.keys():
            key_list = key.split('_')
            if key_list[0].isdigit():
                number_list.append(key_list[0])

        number_list = set(number_list)

        for number in number_list:
            form_id = request.POST.get(number)
            if form_id:
                filtered_post = {key: item for (key, item) in request.POST.items() if key.split('_')[0] == number}
                query_dict = QueryDict('', mutable=True)
                query_dict.update(filtered_post)
                filtered_files = {key: item for (key, item) in request.FILES.items() if key.split('_')[0] == number}
                query_dict_files = QueryDict('', mutable=True)
                query_dict_files.update(filtered_files)
                inline_form = InteractiveElement.get_child_by_name(form_id).get_form()(user=self.request.user, data=query_dict, files=query_dict_files)
                inline_form.set_number(number)
                form_list.append(inline_form)

        form_list_valid = [inline_form.is_valid() for inline_form in form_list]
        form_list_formsets = [all([inline_formset.is_valid() for inline_formset in inline_form.formsets]) for
                              inline_form in form_list]

        form_list_valid.extend(form_list_formsets)

        if form.is_valid() and all(form_list_valid):
            theorem_material = form.save()
            elements = []
            for inline_form in form_list:
                interactive_element = inline_form.save()
                for inline_formset in inline_form.formsets:
                    inline_formset.save()
                elements.append(interactive_element)
            theorem_material.interactiveElements = elements
            theorem_material.save()
            theorem_material = form.save()

            return redirect(theorem_material.get_absolute_url())

        else:
            return self.form_invalid(form, form_list)


class BaseMaterialUpdate(BaseUpdateView):
    template_name = "material/material_form.html"
    page_title = "Edycja materiału"

    def get_context_data(self, **kwargs):
        context = super(BaseMaterialUpdate, self).get_context_data(**kwargs)

        if kwargs.get('form_list'):
            form_list = kwargs.get('form_list')
        else:
            form_list = self.object.get_interactive_elements_form_list(self.request.user)

        form_list.sort(key=lambda x: x.form_number)

        context.update({
            'interactive_elements': InteractiveElementForm.get_interactive_elements(),
            'form_list': form_list,
            'page_title': self.page_title
        })

        return context

    def form_invalid(self, form, form_list=None):
        return self.render_to_response(self.get_context_data(form=form, form_list=form_list))

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()

        form = self.form_class(user=self.request.user, data=request.POST, instance=self.object)

        interactive_elements_instances = self.object.interactiveElements.all()

        form_list = []

        number_list = [key for key in request.POST.keys() if key.isdigit()]

        for interactive_element in interactive_elements_instances:

            if interactive_element.InteractiveType.ID != request.POST.get(str(interactive_element.number)):
                interactive_element.delete()
            else:
                interactive_form = interactive_element.get_form()(user=self.request.user, data=request.POST,
                                                                  files=request.FILES, instance=interactive_element)
                interactive_form.set_number(interactive_element.number)
                form_list.append(interactive_form)

        existing_objects = [str(inline_form.form_number) for inline_form in form_list]

        new_elements = [number for number in number_list if number not in existing_objects]

        for number in new_elements:
            form_id = request.POST.get(number)
            if form_id:
                filtered_post = {key: item for (key, item) in request.POST.items() if key.split('_')[0] == number}
                query_dict = QueryDict('', mutable=True)
                query_dict.update(filtered_post)
                filtered_files = {key: item for (key, item) in request.FILES.items() if key.split('_')[0] == number}
                query_dict_files = QueryDict('', mutable=True)
                query_dict_files.update(filtered_files)
                inline_form = InteractiveElement.get_child_by_name(form_id).get_form()(user=self.request.user,
                                                                                       data=query_dict,
                                                                                       files=query_dict_files)
                inline_form.set_number(number)
                form_list.append(inline_form)

        form_list_valid = [inline_form.is_valid() for inline_form in form_list]
        form_list_formsets = [all([inline_formset.is_valid() for inline_formset in inline_form.formsets]) for
                              inline_form in form_list]

        form_list_valid.extend(form_list_formsets)

        if form.is_valid() and all(form_list_valid):
            theorem_material = form.save()
            elements = []
            for inline_form in form_list:
                interactive_element = inline_form.save()
                for inline_formset in inline_form.formsets:
                    inline_formset.save()
                elements.append(interactive_element)
            theorem_material.interactiveElements = elements
            theorem_material.save()

            return redirect(theorem_material.get_absolute_url())

        else:
            return self.form_invalid(form, form_list)

src/apps/material/views/proof.py
from apps.material.forms import ProofMaterialForm
from apps.material.models import ProofMaterial
from apps.material.views.material import BaseMaterialCreate, BaseMaterialUpdate


class ProofMaterialCreate(BaseMaterialCreate):
    model = ProofMaterial
    form_class = ProofMaterialForm


class ProofMaterialUpdate(BaseMaterialUpdate):
    model = ProofMaterial
    form_class = ProofMaterialForm

src/apps/material/views/theorem.py
from apps.material.forms import TheoremMaterialForm
from apps.material.models import TheoremMaterial
from apps.material.views.material import BaseMaterialCreate, BaseMaterialUpdate


class TheoremMaterialCreate(BaseMaterialCreate):
    model = TheoremMaterial
    form_class = TheoremMaterialForm


class TheoremMaterialUpdate(BaseMaterialUpdate):
    model = TheoremMaterial
    form_class = TheoremMaterialForm

src/apps/material/templates/material/detail.html
{% extends "base/object_detail.html" %}

{% load pdb_filter web_tags %}


{% block extra_panels %}
    {% if object.interactiveElements.all %}
        <div class="panel panel-default">
            <div class="panel-heading">
                Elementy interaktywne
            </div>
            <div class="panel-body form-horizontal">
                {% for interactiveElement in object.interactiveElements.all %}

                    {% interactive_elements_display interactiveElement %}

                {% endfor %}
            </div>
        </div>

    {% endif %}
{% endblock %}

src/apps/material/templates/material/material_choice.html
{% extends "base/type_choice.html" %}

{% block title %} Wybierz konkretny typ materiału {% endblock %}

{% block buttons %}

    <div class="row">
        <a href="{% url 'material:proof:new' %}">
        <div class="col-sm-3">
            <a href="{% url 'material:proof:new' %}">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-3">
                                <i class="fa fa-comments"></i>
                            </div>
                            <div class="col-xs-9 text-right">
                                <div>Dowód</div>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-sm-3">
            <a href="{% url 'material:definition:new' %}">
                <div class="panel panel-green">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-3">
                                <i class="fa fa-tasks"></i>
                            </div>
                            <div class="col-xs-9 text-right">
                                <div>Definicja</div>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-sm-3">
            <a href="{% url 'material:example:new' %}">
                <div class="panel panel-yellow">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-3">
                                <i class="fa fa-shopping-cart"></i>
                            </div>
                            <div class="col-xs-9 text-right">
                                <div>Przykład</div>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-sm-3">
            <a href="{% url 'material:theorem:new' %}">
                <div class="panel panel-red">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-3">
                                <i class="fa fa-support"></i>
                            </div>
                            <div class="col-xs-9 text-right">
                                <div>Twierdzenie</div>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
        </div>
    </div>






{% endblock %}

src/apps/material/templates/material/material_form.html
{% extends "web/base.html" %}

{% block content %}
    <legend>{{ page_title }}</legend>

    <form action="" method="post" enctype="multipart/form-data">

        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#base_data" aria-controls="base_data" role="tab"
                                                      data-toggle="tab">Dane podstawowe</a></li>
            <li role="presentation"><a href="#interactivity" aria-controls="interactivity" role="tab" data-toggle="tab">Elementy
                interaktywne</a></li>
        </ul>

        <div class="tab-content">

            <fieldset role="tabpanel" class="tab-pane active" id="base_data">
                <div class="form-horizontal">
                    {% load crispy_forms_tags %}
                    {% crispy form crispy_helper %}
                </div>
            </fieldset>
            <fieldset role="tabpanel" class="tab-pane" id="interactivity">
                <div class="form-horizontal">

                    <div id="interactive_type_buttons">
                        {% for item_type in interactive_elements %}
                            <button data-href="{{ item_type.href }}"
                                    class="btn btn-primary">{{ item_type.text }}</button>
                        {% endfor %}
                    </div>

                    <div class="panel-group accordion" id="forms" role="tablist" aria-multiselectable="true">
                        {% for form in form_list %}
                            {% include "interactivity/form_formset.html" with form=form %}
                        {% endfor %}
                    </div>
                </div>
            </fieldset>

        </div>
        <input type="submit" value="Zapisz" class="btn btn-success">

    </form>


{% endblock %}

src/apps/material/templates/material/material_list.html
{% extends "base/object_list.html" %}

{% block title %} Materiały {% endblock %}

{% block add_new %}
    <a href="{% url 'material:new' %}" class="btn btn-primary">Dodaj nowy</a>
{% endblock %}

{% block additional_th %}
    <th>Typ</th>
{% endblock %}

{% block additional_td %}
    <td>{{ object.get_visible_name }}</td>
{% endblock %}

{% block preview %}
    <a href="{% url 'web:preview' 'material' object.id %}">Podejrzyj</a>
{% endblock %}

{% block public_preview %}
    <a href="{% url 'web:preview' 'material' object.id %}">Podejrzyj</a>
{% endblock %}

{% block public_additional_th %}
    <th>Typ</th>
{% endblock %}

{% block public_additional_td %}
    <td>{{ object.get_visible_name }}</td>
{% endblock %}