src/api/urls.py
from django.conf.urls import patterns, include, url
from rest_framework.routers import DefaultRouter

from .courses.views import CourseViewSet, ModuleViewSet
from .materials.views import MaterialViewSet, ExampleMaterialViewSet, \
    DefinitionMaterialViewSet, ProofMaterialViewSet, \
    TheoremMaterialViewSet
from .theory.views import TheoremViewSet, DefinitionViewSet, \
    ExerciseViewSet, ProofViewSet

router = DefaultRouter()
router.register(r'courses', CourseViewSet)
router.register(r'modules', ModuleViewSet)

router.register(r'materials', MaterialViewSet)

router.register(r'exampleMaterials', ExampleMaterialViewSet)
router.register(r'proofMaterials', ProofMaterialViewSet)
router.register(r'definitionMaterials', DefinitionMaterialViewSet)
router.register(r'theoremMaterials', TheoremMaterialViewSet)

router.register(r'proofs', ProofViewSet)
router.register(r'exercises', ExerciseViewSet)
router.register(r'definitions', DefinitionViewSet)
router.register(r'theorems', TheoremViewSet)

urlpatterns = patterns('',

                       url(r'^', include(router.urls)),
                       )

src/generatorKursow/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns(
    '',

    url(r'^', include('web.urls', namespace='web')),

    url(r'^theory/', include('apps.theory.urls', namespace='theory')),
    url(r'^course/', include('apps.course.urls', namespace='course')),
    url(r'^module/', include('apps.module.urls', namespace='module')),
    url(r'^material/', include('apps.material.urls', namespace='material')),
    url(r'^interactivity/', include('apps.interactivity.urls', namespace='interactivity')),

    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^docs/', include('rest_framework_swagger.urls')),

    url(r'^account/plugins/', include('plugins.urls', namespace="plugins")),
    url(r'^account/templates/', include('userTemplates.urls', namespace='userTemplates')),
    url(r'^login', 'django.contrib.auth.views.login', name="login"),
    url(r'^logout', 'django.contrib.auth.views.logout', {'next_page': '/'}, name="logout"),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^accounts/', include('registration.backends.simple.urls', namespace='accounts')),

    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

src/userTemplates/urls.py
from django.conf.urls import patterns, url

from userTemplates import views


urlpatterns = patterns(
    '',

    url(r'^$',
        views.IndexView.as_view(),
        name='index'),
    url(r'^upload/$',
        views.UploadTemplateView.as_view(),
        name='upload-template'),
    url(r'^(?P<pk>[A-Za-z]+)/delete/$',
        views.request_delete_template,
        name="delete"),
    url(r'^(?P<pk>[A-Za-z]+)/delete/confirm$',
        views.delete_template,
        name="delete-confirm"),

)

src/web/urls.py
from django.conf.urls import patterns, url

from web.views import *


urlpatterns = patterns(
        '',

        url(r'^$',
            home,
            name='home'),

        url(r'^download/course/(?P<id>[\d]+)/$',
            choose_course_template,
            name='download-course'),
        url(r'^download/module/(?P<id>[\d]+)/$',
            choose_module_template,
            name='download-module'),
        url(r'^download/material/(?P<id>[\d]+)/$',
            choose_material_template,
            name='download-material'),

        url(r'^download/(?P<item_type>course|module|material)/(?P<id>[\d]+)/without/template/$',
            download,
            name='download-without-template'),
        url(
            r'^download/(?P<item_type>course|module|material)/(?P<id>[\d]+)/using/template/(?P<template_name>[A-Za-z]+)/$',
            download,
            name='download-using-template'),

        url(r'^preview/(?P<item_type>course|module|material)/(?P<id>[\d]+)/$',
            preview,
            name='preview')

)

src/userTemplates/models.py
from django.db import models

# Create your models here.

src/userTemplates/forms.py
# -*- coding: utf-8 -*-
import zipfile

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms


class UploadNewTemplateForm(forms.Form):

    file = forms.FileField()

    def __init__(self, *args, **kwargs):
        super(UploadNewTemplateForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-4'
        self.helper.field_class = 'col-lg-8'
        self.helper.add_input(Submit('submit', 'Zapisz'))

    def clean_file(self, *args, **kwargs):

        _file = self.cleaned_data['file']
        ext = _file.name.split('.')[-1]

        if not zipfile.is_zipfile(_file):
            raise forms.ValidationError(u'Przesłałeś plik z rozszerzeniem %s. Prześlij .zip!' % ext)

        return _file

src/userTemplates/views.py
# -*- coding:utf8 -*-

import shutil
import os
import zipfile

from django.conf import settings
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import redirect, render
from django.views.generic.edit import FormView

from userTemplates.forms import UploadNewTemplateForm


class IndexView(FormView):
    template_name = 'userTemplates/index.html'
    form_class = UploadNewTemplateForm
    success_url = reverse_lazy('userTemplates:index')

    def get_context_data(self, **kwargs):
        ret = super(IndexView, self).get_context_data(**kwargs)

        if not os.path.isdir(settings.BASE_DIR + '/userTemplates/uploaded'):
            os.mkdir(settings.BASE_DIR + '/userTemplates/uploaded')

        ret.update({
            'templates': os.listdir(
                settings.BASE_DIR + '/userTemplates/uploaded')
        })

        return ret


class UploadTemplateView(FormView):
    template_name = 'userTemplates/upload.html'
    form_class = UploadNewTemplateForm
    success_url = reverse_lazy('userTemplates:index')

    def form_valid(self, form):

        _file = form.cleaned_data['file']
        output_path = os.path.join(settings.BASE_DIR, 'userTemplates/uploaded')

        with zipfile.ZipFile(_file, 'r') as archive:
            for name in archive.namelist():
                archive.extract(name, output_path)

        _file.close()

        return super(UploadTemplateView, self).form_valid(form=form)


def request_delete_template(request, pk):
    return render(request, 'userTemplates/delete.html', {'name' : pk})


def delete_template(request, pk):
    success_url = reverse_lazy('userTemplates:index')
    output_path = os.path.join(settings.BASE_DIR, 'userTemplates/uploaded')
    shutil.rmtree(os.path.join(output_path, pk))
    return redirect(success_url)


# class DeleteTemplateView(ModalDeleteView, DeleteView):
#     def __init__(self, *args, **kwargs):
#         self.model = UserTemplate
#         self.title = "Usuwanie obiektu"
#         self.description = "Jesteś pewny?"
#
#     def dispatch(self, request, *args, **kwargs):
#         self.object = self.get_object()
#         return super(DeleteTemplateView, self).dispatch(
#             request, *args, **kwargs)
#
#     def delete(self, request, *args, **kwargs):
#         reversed = reverse('userTemplates:delete-confirm')
#         self.response = ModalJsonResponseRedirect(reversed)
#         super(DeleteTemplateView, self).delete(request, *args, **kwargs)


# class DeleteTemplateView(DeleteView):
#     template_name = 'userTemplates/delete.html'
#     model = UserTemplate
#     success_url = reverse_lazy('userTemplates:index')
#
#     def post(self, request, *args, **kwargs):
#
#         self.object = self.get_object()
#         output_path = os.path.join(
#             settings.BASE_DIR, 'userTemplates/uploaded')
#
#         import shutil
#         shutil.rmtree(os.path.join(output_path, self.object.name))
#
#         return redirect(self.success_url)

src/userTemplates/templates/userTemplates/choose.html
{% extends "web/base.html" %}

{% load pdb_filter %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Wybierz szablon
            </h1>

            <ul>
                <li>
                    <a href="{% url 'web:download-without-template' item_type item_id %}">domyślnie (bez własnego szablonu)</a>
                </li>
            {% for template in templates %}

                <li>
                <a href="{% url 'web:download-using-template' item_type item_id template %}">{{ template }}</a>
                </li>
            {% endfor %}
            </ul>

        </div>
    </div>
{% endblock %}

src/userTemplates/templates/userTemplates/delete.html
{% extends "web/base.html" %}

{% block content %}

<h1>Usuwanie szablonu</h1>
<p>Czy na pewno chcesz usunąć szablon {{ name }}?</p>

<p>
    <a href="{% url 'userTemplates:delete-confirm' name %}" class="btn btn-danger">Usuń</a>
    <a href="{% url 'userTemplates:index' %}" class="btn btn-default">Anuluj</a>
</p>

{% endblock %}

src/userTemplates/templates/userTemplates/index.html
{% extends "web/base.html" %}

{% load pdb_filter %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Lista dostępnych szablonów
            </h1>

            <p><a href="{% url 'userTemplates:upload-template' %}" class="btn btn-primary">Dodaj nowy</a></p>

            <table class="datatable table">
                <thead>
                <tr>
                    <th>Nazwa</th>
                    <th></th>
                </tr>
                </thead>

                <tbody>
                {% for template in templates %}

                    <tr>
                        <td>{{ template }}</td>

                        <td>
                            <a href="{% url 'userTemplates:delete' template %}">Usuń</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
{% endblock %}

src/userTemplates/templates/userTemplates/upload.html
{% extends "web/base.html" %}

{% load pdb_filter %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Dodaj własny szablon

            </h1>
            <p>
                {% load crispy_forms_tags %}
                {% crispy form %}
            </p>
        </div>
    </div>
{% endblock %}